spring:
  datasource:
    url: jdbc:mysql://localhost/cloud-dictionary?useSSL=false&serverTimezone=GMT%2B8&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
    username: root
    password: dbadmin
